name: 🚀 CI/CD Development

on:
  push:
    branches:
      - farell
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Docker-Test

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install Dependencies
        run: npm install

      - name: 🔐 Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🛠 Build Docker Image
        run: docker build -t kresnandaf/farell-profile:latest .

      - name: 📤 Push Docker Image
        run: docker push kresnandaf/farell-profile:latest

      - name: 🚢 Deploy to VPS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔁 Pulling latest Docker image..."
            docker pull kresnandaf/farell-profile:latest

            echo "🛑 Stopping and removing old container (if exists)..."
            docker stop farell-profile || true
            docker rm farell-profile || true

            echo "🚀 Running new container..."
            docker run -d \
              --name farell-profile \
              --restart unless-stopped \
              -p "${{ secrets.PORT }}":3000 \
              kresnandaf/farell-profile:latest

            echo "🧹 Cleaning up unused Docker resources..."
            docker system prune -f

            echo "✅ Deployment to Development environment completed successfully!"