name: CI/CD for Node.js Portfolio (Docker)

on:
  push:
    branches:
      - main  # Workflow akan berjalan pada saat push ke cabang main
  pull_request:
    branches:
      - main  # Workflow juga akan berjalan pada saat pull request ke cabang main

jobs:
  # Job untuk Build Docker image
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout repository

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1  # Setup Docker Buildx

    - name: Build Docker image
      run: docker build -t my-node-app .  # Membangun Docker image dengan nama "my-portfolio-app"

    - name: Run tests (optional)
      run: |
        docker run --rm my-node-app npm test  # Menjalankan pengujian aplikasi jika ada

  # Job untuk deploy ke VPS
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Pastikan deploy dijalankan setelah build selesai

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout repository

    - name: Set up SSH for VPS
      uses: webfactory/ssh-agent@v0.5.3  # Menggunakan SSH Agent untuk VPS
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key yang disimpan di GitHub Secrets

    - name: Deploy to VPS using Docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          # Arahkan ke direktori aplikasi di VPS Anda
          cd /farell-profile

          # Tarik Docker image terbaru dari Docker Hub (jika Anda mempush image ke Docker Hub) atau build ulang di VPS
          docker build -t my-portfolio-app .

          # Jalankan container dengan image yang baru
          docker run -d -p 3001:3001 --restart always --name portfolio-app my-portfolio-app
        EOF
